### ISSUE TITLE
Search Viewがうまくできない。どうやろう

### ISSUE THREAD

**Issue by OuchiTakeru** [kantasasakimaru/location_alarm#10]

**Comment by OuchiTakeru** [comment]
https://qiita.com/Xdaichi/items/e6234b336219120a76e4

http://abj-app-dev.hatenablog.com/entry/2015/10/21/141535

https://qiita.com/ryokosuge/items/186c525e0744903ee8ce

**Comment by atomic-kanta-sasaki** [comment]
これ最悪titleのDBをwhere区使って引っ張ってくる感じで暫定対応って感じでもいいかもしれない.
ここ時間かかるかもだから間に合わなさそうだったらアラートあげてほしい

**Comment by atomic-kanta-sasaki** [comment]
https://qiita.com/sass9872/items/18244ff81a9efcfcd251
searchViewにこだわらないでこのやり方で部分一致してるDBのレコードを表示するとかいいかもしれないい

**Comment by atomic-kanta-sasaki** [comment]
プロジェクト終了のため
